### PR TITLE
Added top HUD

### PR DESCRIPTION
**Pull request by ben260**
Top HUD displays time remaining, customers remaining and reputation points.

### CODE REVIEW

**Comment by vkczyz** [comment]
There's two bugs I've noticed here:

- Not being able to move up and right, which you noted earlier
- My game window seems to be extremely zoomed in when testing this on Linux. I included an image below.

image

I managed to pin the first issue down to the chef speed being decreased from 200 to 10. I've set this back to its original value, which solved the problem. It is odd that the speed was only affected in two directions; we'll should investigate that further.

As for the second issue, it seems to be caused by setting the projection matrix to the HUD stage camera. I'm not sure on the details of how the HUD works, but I'll look at it later if you don't get to it before me.

**Review by vkczyz — CHANGES_REQUESTED** [review]
Blocking this until we can eliminate the zoom effect.

It might be system-specific? I hope someone else can test it on their device (I'm especially curious if it occurs on a Mac).

EDIT: Looking closer, I suspect that the viewport generated in the `TopHud` constructor is responsible. It doesn't use any parameters, so I suspect it just picks some bad defaults.

**Comment by ben260** [comment]
> Blocking this until we can eliminate the zoom effect.
> 
> It might be system-specific? I hope someone else can test it on their device (I'm especially curious if it occurs on a Mac).
> 
> EDIT: Looking closer, I suspect that the viewport generated in the `TopHud` constructor is responsible. It doesn't use any parameters, so I suspect it just picks some bad defaults.

I've commented out the thing that might be responsible and it still works. Hopefully it's solved the zoom error?

**Comment by vkczyz** [comment]
It doesn't seem like this fix did anything.

However, I did learn that the zoom issue is dependent on the space the game window has when it starts. If it has less space than it should (e.g. the window is resized before loading), then it will stay locked in a terrible resolution and cannot be freed from it. If the game *does* have enough space, everything looks okay.

This means it's not as big of a deal as I thought, since the conditions it happens in are fairly unique. Maybe it'd be an issue if someone tried playing the game on too small a resolution, but fixing that doesn't need to be an immediate priority.

I'll unblock the PR.

**Review by vkczyz — APPROVED** [review]
Approved

**Comment by mattrohatynskyj** [comment]
> It doesn't seem like this fix did anything.
> 
> However, I did learn that the zoom issue is dependent on the space the game window has when it starts. If it has less space than it should (e.g. the window is resized before loading), then it will stay locked in a terrible resolution and cannot be freed from it. If the game _does_ have enough space, everything looks okay.
> 
> This means it's not as big of a deal as I thought, since the conditions it happens in are fairly unique. Maybe it'd be an issue if someone tried playing the game on too small a resolution, but fixing that doesn't need to be an immediate priority.
> 
> I'll unblock the PR.

What do you think about locking the screen size (ie setting resizable to false), or instead using fullscreen mode? I feel like this should alleviate the problems which are occuring.

**Review by SaltyWriter38 — APPROVED** [review]

**Comment by vkczyz** [comment]
We should try both options and see which works better. Our current approach *does* handle resizing well once it had loaded the initial content; it's just bad if it starts at a poor resolution.
―Matthew

**Pull request merged**
