### PR TITLE
Added Ashley ECS

### PR DESCRIPTION
**Pull request by ben260**
Added Ashley to dependencies
Added Cook1 and Cook2 entities
Added basic entity renderer.

### CODE REVIEW

**Review by mattrohatynskyj — APPROVED** [review]
did some testing on your branch, its a much better approach at rendering entities. ill approve your pull request with the idea of deleting Chef.java after merging as it is now redundant

**Review by vkczyz — CHANGES_REQUESTED** [review]
This is much closer to a real ECS system and serves as an excellent base to build on top of. Good work.

One thing that seems ugly to me is the `createCook1()` and `createCook2()`-type functions. These seem like they would clutter the codebase with hardcoded objects over time as we make more types of entities. The way I've addressed this in another project is by having an external data file (can be JSON, XML, or whatever) that describes each entity and its components. Then you could load a chef by doing something like `factory.loadEntity("entity1.json")`.

Like with the redundant `Chef` class, there's also a lot of old code that's been commented out instead of deleted. Let's remove all that before merging.

**Review by vkczyz — APPROVED** [review]
I removed the old code.

**Comment by ben260** [comment]
> This is much closer to a real ECS system and serves as an excellent base to build on top of. Good work.
> 
> One thing that seems ugly to me is the `createCook1()` and `createCook2()`-type functions. These seem like they would clutter the codebase with hardcoded objects over time as we make more types of entities. The way I've addressed this in another project is by having an external data file (can be JSON, XML, or whatever) that describes each entity and its components. Then you could load a chef by doing something like `factory.loadEntity("entity1.json")`.
> 
> Like with the redundant `Chef` class, there's also a lot of old code that's been commented out instead of deleted. Let's remove all that before merging.

I agree sounds like a file to store the description of entities would be cleaner. I've added a comment in the code to think about it later.

**Pull request merged**
