### PR TITLE
Create moveable Player object

### PR DESCRIPTION
**Pull request by vkczyz**
Added a `Player` object that can moved around the screen with the arrow keys. Currently using a placeholder texture.

### CODE REVIEW

**Review by ben260 — APPROVED** [review]

**Review by ben260 — CHANGES_REQUESTED** [review]
Doesn't work :(

**Comment by vkczyz** [comment]
I still need to fix this

**Comment by vkczyz** [comment]
I've brought this in line with the master branch. I also changed the position and speed to more appropriate values.

**Comment by vkczyz** [comment]
Reimplemented elsewhere.

**Pull request closed without merging**
