### PR TITLE
Implemented collision

### LINKED ISSUE #9: Implement collision system
Probably through a `CollisionComponent`.

### PR DESCRIPTION
**Pull request by vkczyz**
Simple AABB collision :)

### CODE REVIEW

**Comment by vkczyz** [comment]
@mattrohatynskyj also added chef-switching.

It's pretty funny, but the second chef is able to push the first one around. I don't know whether to consider this a bug or not. Do we want chefs to be able to push each other around?

**Comment by mattrohatynskyj** [comment]
> @mattrohatynskyj also added chef-switching.
> 
> It's pretty funny, but the second chef is able to push the first one around. I don't know whether to consider this a bug or not. Do we want chefs to be able to push each other around?

I would say probably not? Particularly the case where a chef has the "BusyComponent" meaning they are occupied with a task, they probably should not be moveable from the task they are doing.

However, this also isn't as high of a priority as getting the game logic to work properly, but would be nice to implement after that.

**Review by ben260 — APPROVED** [review]
Very nice

**Review by mattrohatynskyj — APPROVED** [review]
nice

**Pull request merged**
